Fix: ensure correct handling of mtable in LaTeX output
asnunes/mathml-to-latex pull request #24
Opened 2024-06-06 06:34 UTC by yuxuan-wei118

The original code may mistranslate the <mtable> tag. I fixed the issue by using array{ccc} to express the final output, and it should be able to translate to Latex correctly now. I also add a few tests to prove that.

2024-06-06 06:37 UTC, yuxuan-wei118 commented
Although it can translate correctly, the new update code fails to pass a few tests involving the <mfence> tag, which may have already been removed from the relevant web standards. So, any comment or recommended approach to fix the issue?

2024-06-08 21:02 UTC, asnunes commented
Hi, @yuxuan-wei118. Thanks for your contribution! However, the issue is not clear to me. Besides the test you added, could you provide some examples of input, the expected result, and the result before the changes, highlighting the broken/missing part? I would like to understand the problem a little better.

2024-06-11 23:04 UTC, yuxuan-wei118 commented
Hi @asnunes. Thank you for your reply! One mistranslating example is the code below.
```
<math display="block">
  <mfrac>
    <mi>A</mi>
    <mn>2</mn>
  </mfrac>
  <mo>=</mo>
  <mrow>
    <mo>(</mo>
    <mtable>
      <mtr>
        <mtd><mn>1</mn></mtd>
        <mtd><mn>2</mn></mtd>
        <mtd><mn>3</mn></mtd>
      </mtr>
      <mtr>
        <mtd><mn>4</mn></mtd>
        <mtd><mn>5</mn></mtd>
        <mtd><mn>6</mn></mtd>
      </mtr>
      <mtr>
        <mtd><mn>7</mn></mtd>
        <mtd><mn>8</mn></mtd>
        <mtd><mn>9</mn></mtd>
      </mtr>
    </mtable>
    <mo>)</mo>
  </mrow>
</math>
```

The expected result should be that:
![Expected result](https://github.com/asnunes/mathml-to-latex/assets/154886963/ace59f09-4979-4b35-8633-22fd9c0cc65d)

However, the original code will translate the input into the following: 
![Original result](https://github.com/asnunes/mathml-to-latex/assets/154886963/4ff30669-8252-4160-8c2a-2ba828d3ddf9)
which is an illegal syntax missing \begin{array} {ccc} and end {array}.

Please feel free to give more comments!

2024-06-29 17:46 UTC, asnunes requested changes

2024-06-29 17:46 UTC, asnunes commented on __tests__/index.test.ts
> +      //console.log('result', result)
dead commented code

2024-06-29 17:46 UTC, asnunes commented on __tests__/index.test.ts
> +    console.log(result);
forgot console.log

2024-06-29 17:46 UTC, asnunes commented on src/data/usecases/mathml-to-latex-convertion/converters/mtable.ts
> +      //console.warn('dimensionString is undefined or null, default to 0.0');
dead console.log

2024-06-29 17:46 UTC, asnunes commented on src/data/usecases/mathml-to-latex-convertion/converters/mtable.ts
> +    const columnwidth = this._mathmlElement.attributes['columnwidth'];
unnecessary comment and case: `columnwidth` -> `columnWidth`

2024-06-29 17:46 UTC, asnunes commented on src/data/usecases/mathml-to-latex-convertion/converters/mtable.ts
> +    const columnwidthCm = widthValues.map((value) => value * 0.423);
case

2024-06-29 17:46 UTC, asnunes commented on src/data/usecases/mathml-to-latex-convertion/converters/mtable.ts
> +    const columnwidthCm = widthValues.map((value) => value * 0.423);
`TableRows` -> `tableRows`

2024-06-29 17:46 UTC, asnunes commented on src/data/usecases/mathml-to-latex-convertion/converters/mtable.ts
> +    const columnspacing = this._mathmlElement.attributes['columnspacing'];
case

2024-06-29 17:46 UTC, asnunes commented on src/data/usecases/mathml-to-latex-convertion/converters/mtable.ts
> +    const columnspacingValue = parseFloat(columnspacing);
case

2024-06-29 17:46 UTC, asnunes commented on src/data/usecases/mathml-to-latex-convertion/converters/mtable.ts
> +    const columnspacingCm = isNaN(columnspacingValue) ? 0 : columnspacingValue * 0.423;
case

2024-06-29 17:46 UTC, asnunes commented on src/data/usecases/mathml-to-latex-convertion/converters/mtable.ts
> +    let tableRows = latex.split('\\\\');
what is the semantic diff between tableRows and TableRows?

2024-06-29 17:46 UTC, asnunes commented on src/data/usecases/mathml-to-latex-convertion/converters/mtable.ts
> +    const rowspacing = this._mathmlElement.attributes['rowspacing'];
uncessary comment

2024-06-29 17:46 UTC, asnunes commented on src/data/usecases/mathml-to-latex-convertion/converters/mtable.ts
> +    const rowlines = this._mathmlElement.attributes['rowlines'];
uncessary comment

2024-06-29 17:46 UTC, asnunes commented on src/data/usecases/mathml-to-latex-convertion/converters/mtable.ts
> +    const columnlines = this._mathmlElement.attributes['columnlines'];
uncessary comment

2024-06-29 17:46 UTC, asnunes commented on src/data/usecases/mathml-to-latex-convertion/converters/mtable.ts
> +    //
uncessary comment

2024-06-29 17:46 UTC, asnunes commented on src/data/usecases/mathml-to-latex-convertion/converters/mtable.ts
> +    const framespacing = this._mathmlElement.attributes['framespacing'];
uncessary comment
case

2024-06-29 17:46 UTC, asnunes commented on src/data/usecases/mathml-to-latex-convertion/converters/mtable.ts
> +    let Tablerows = latex.split('\\\\');
case

2024-06-29 17:52 UTC, asnunes requested changes
Hi, @yuxuan-wei118. The feature are now clear to me, but I have some concerns that need to be addressed before merging:

1. Some of the existing tests are not passing, like shown in the workflow I run and in the text below. Do you disagree with the expected result or the code should be changed to make these tests pass:

```
FAIL __tests__/index.test.ts
  ● Console

    console.log
      \left(\right. \begin{array}{ccc}{1 }&{ 2 }&{ 3 } \\{ 4 }&{ 5 }&{ 6 } \\{ 7 }&{ 8 }&{ 9}\end{array} \left.\right)

      at Object.<anonymous> (__tests__/index.test.ts:1184:13)

  ● #convert › given mfenced tag › when mfenced represents a matrix › given math string with mtable, mtr and mtd tag › with open attribute as [ › returns a bmatrix representation in latex

    expect(received).toBe(expected) // Object.is equality

    Expected: "A = \\begin{bmatrix} x & y \\\\ z & w \\end{bmatrix}"
    Received: "A = \\begin{bmatrix} \\begin{array}{cc}{x }&{ y } \\\\{ z }&{ w}\\end{array} \\end{bmatrix}"

  ● #convert › given mfenced tag › when mfenced represents a matrix › given math string with mtable, mtr and mtd tag › with open attribute as ( › returns a pmatrix representation in latex

    expect(received).toBe(expected) // Object.is equality

    Expected: "A = \\begin{pmatrix} x & y \\\\ z & w \\end{pmatrix}"
    Received: "A = \\begin{pmatrix} \\begin{array}{cc}{x }&{ y } \\\\{ z }&{ w}\\end{array} \\end{pmatrix}"

  ● #convert › given mfenced tag › when mfenced represents a matrix › given math string with mtable, mtr and mtd tag › with open attribute as | › returns a vmatrix representation in latex

    expect(received).toBe(expected) // Object.is equality

    Expected: "A = \\begin{vmatrix} x & y \\\\ z & w \\end{vmatrix}"
    Received: "A = \\begin{vmatrix} \\begin{array}{cc}{x }&{ y } \\\\{ z }&{ w}\\end{array} \\end{vmatrix}"

  ● #convert › given mfenced tag › when mfenced represents a matrix › given math string with mtable, mtr and mtd tag › with open attribute as { › returns a Bmatrix representation in latex

    expect(received).toBe(expected) // Object.is equality

    Expected: "A = \\begin{Bmatrix} x & y \\\\ z & w \\end{Bmatrix}"
    Received: "A = \\begin{Bmatrix} \\begin{array}{cc}{x }&{ y } \\\\{ z }&{ w}\\end{array} \\end{Bmatrix}"

  ● #convert › given mfenced tag › when mfenced represents a matrix › given math string with mtable, mtr and mtd tag › with open attribute as || › returns a Vmatrix representation in latex

    expect(received).toBe(expected) // Object.is equality

    Expected: "A = \\begin{Vmatrix} x & y \\\\ z & w \\end{Vmatrix}"
    Received: "A = \\begin{Vmatrix} \\begin{array}{cc}{x }&{ y } \\\\{ z }&{ w}\\end{array} \\end{Vmatrix}"

  ● #convert › given mfenced tag › when mfenced represents a matrix › given math string with mtable, mtr and mtd tag › without open attribute › returns a matrix representation in latex

    expect(received).toBe(expected) // Object.is equality

    Expected: "A = \\begin{bmatrix} x & y \\\\ z & w \\end{bmatrix}"
    Received: "A = \\begin{bmatrix} \\begin{array}{cc}{x }&{ y } \\\\{ z }&{ w}\\end{array} \\end{bmatrix}"

  ● #convert › given mfenced tag › when mfenced represents a matrix › given math string with partial function › returns latex partial function representation

    expect(received).toBe(expected) // Object.is equality

    Expected: "f \\left(x\\right) = \\left{\\begin{matrix} x^{2} , x < 0 \\\\ e^{x} , x \\geq 0 \\end{matrix}\\right"
    Received: "f \\left(x\\right) = \\left{\\begin{matrix} \\begin{array}{c}{ x^{2} , x < 0 } \\\\{ e^{x} , x \\geq 0}\\end{array} \\end{matrix}\\right"

  ● #convert › given mfenced tag › when mfenced represents a matrix › given math string with nested mtables › adds matrix to inner table

    expect(received).toBe(expected) // Object.is equality

    Expected: "\\begin{bmatrix} \\begin{matrix}a_{11} & a_{12}\\end{matrix} & \\begin{matrix}\\ldots & \\ldots\\end{matrix} & a_{1 n} \\\\ \\begin{matrix}a_{21} & a_{22}\\end{matrix} & \\begin{matrix}\\ddots & \\end{matrix} & a_{2 n} \\\\ \\begin{matrix}\\begin{matrix}\\vdots & \\vdots\\end{matrix} \\\\ \\begin{matrix}a_{m 1} & a_{m 2}\\end{matrix}\\end{matrix} & \\begin{matrix}\\begin{matrix} & \\ddots\\end{matrix} \\\\ \\begin{matrix}\\ldots & \\ldots\\end{matrix}\\end{matrix} & \\begin{matrix}\\vdots \\\\ a_{m n}\\end{matrix} \\end{bmatrix}"
    Received: "\\begin{bmatrix} \\begin{array}{ccc}{\\begin{array}{cc}{a_{11} }}&{{ a_{12}}\\end{array} }&{ \\begin{array}{cc}{\\ldots }}&{{ \\ldots}\\end{array} }& a_{1 n} \\\\{ \\begin{array}{cc}{a_{21} }}&{{ a_{22}}\\end{array} }&{ \\begin{array}{cc}{\\ddots }}&{{ }\\end{array} }& a_{2 n} \\\\{ \\begin{array}{c}{\\begin{array}{cc}{\\vdots }}}&{{{ \\vdots}\\end{array} } } \\\\{{ \\begin{array}{cc}{a_{m 1} }}}&{{{ a_{m 2}}\\end{array}}\\end{array} }&{ \\begin{array}{c}{\\begin{array}{cc}{ }}}&{{{ \\ddots}\\end{array} } } \\\\{{ \\begin{array}{cc}{\\ldots }}}&{{{ \\ldots}\\end{array}}\\end{array} }&{ \\begin{array}{c}{\\vdots } } \\\\{{ a_{m n}}\\end{array}}\\end{array} \\end{bmatrix}"
  ```

2. I didn't get the expected behavior for `hspace`. Is there a case where you do not add `hspace`? I am concerned about adding unnecessary text to the final LaTeX output. It should be as clean as possible and only include the information present in the original MathML text.

3. We also need to point out the issues in the reviewed code.

Once again, thanks for taking the time to add this PR. I will be happy to merge and publish the changes once these issues are addressed.

2024-08-27 18:29 UTC, yuxuan-wei118 commented
Hi @asnunes.

1. For the first concern, I think we should change code to make these tests pass.

2. For the second issue, the addition of `hspace` aims to address any possible additional formatting syntax that may appeared in `mtable` tag. 

Here is an example mathml code that you can see `mtable` may include additional formatting syntax: 
` <math xmlns="http://www.w3.org/1998/Math/MathML"><mtable columnwidth="3em 0.05em 3em 3em 3em 3em" columnspacing="0.0em" rowspacing="0.05ex" rowlines="solid" columnlines="solid" frame="solid" framespacing="0.0em 0ex"><mtr><mtd><mi>x</mi></mtd><mtd><mspace width="0.0em" height="2.5ex" depth="1.0ex"/></mtd><mtd><mo>&#x2212;</mo><mn>1</mn></mtd><mtd><mn>0</mn></mtd><mtd><mn>1</mn></mtd><mtd><mn>2</mn></mtd></mtr><mtr><mtd><mi>g</mi><mrow><mo>(</mo><mi>x</mi><mo>)</mo></mrow></mtd><mtd><mspace width="0.0em" height="2.5ex" depth="1.0ex"/></mtd><mtd><mn>6</mn></mtd><mtd><mn>4</mn></mtd><mtd><mn>2</mn></mtd><mtd><mo>&#x2212;</mo><mn>1</mn></mtd></mtr><mtr><mtd><msup><mi>g</mi><mo>'</mo></msup><mrow><mo>(</mo><mi>x</mi><mo>)</mo></mrow></mtd><mtd><mspace width="0.0em" height="2.5ex" depth="1.0ex"/></mtd><mtd><mo>&#x2212;</mo><mn>1</mn></mtd><mtd><mo>&#x2212;</mo><mn>7</mn></mtd><mtd><mo>&#x2212;</mo><mn>2</mn></mtd><mtd><mo>&#x2212;</mo><mn>3</mn></mtd></mtr></mtable></math>`
Adding `hspace` makes the output Latex code closer to the intended format given by mathml. But it is also true that it may be redundant in some cases. 

3. For the third issue, we can do this after resolving all issues above. 

Please feel free to give more comments!

2026-05-07 11:44 UTC, closed without merging